import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import AdminDashboard from './AdminDashboard'
import Login from './sign/login/login'
import Register from './sign/register/register'
import Homepage from './sign/homepage/homepage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <AdminDashboard/> */}
        <Login/>
        <Register/>
        <Homepage/>
      
      </main>
    </>
  )
}
